DROP TABLE IF EXISTS Ordered_products;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS User;

CREATE TABLE User (
	Id INT AUTO_INCREMENT PRIMARY KEY
	, Name VARCHAR(60) NOT NULL
	, Email VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE Product (
	Id INT AUTO_INCREMENT PRIMARY KEY
	, Name VARCHAR(60) NOT NULL
	, Quantity INT NOT NULL
	, Price DOUBLE NOT NULL
);

CREATE TABLE Orders (
	Id INT AUTO_INCREMENT PRIMARY KEY
	, User_id INT NOT NULL
	, Phone VARCHAR(20) NOT NULL
	, card_number VARCHAR(10) NOT NULL
	, Address VARCHAR(100) NOT NULL
	, Comment VARCHAR(100) NOT NULL
	, FOREIGN KEY (User_id) REFERENCES User(Id)
);

CREATE TABLE Ordered_products (
	Product_id INT NOT NULL
	, Order_id INT NOT NULL
	, FOREIGN KEY (Product_id) REFERENCES Product(Id)
	, FOREIGN KEY (Order_id) REFERENCES Orders(Id)
);
